#!/usr/bin/env node
/**
 * Canonical-format check/fix for handwritten JSON under data/.
 *
 * Canonical form: JSON.stringify(JSON.parse(text), null, 2) + "\n" with
 * the authored key order preserved (JSON.parse keeps insertion order;
 * keys are never sorted). This matches the dominant convention in the
 * tree - the importer-written community manifests round-trip exactly.
 *
 * Known divergence, by design: the gezel-authored bundled manifests
 * (~5.1k files) were formatted by Biome, which inlines short arrays
 * based on line width. Those files are semantically identical but not
 * byte-canonical; running --write would reflow them. Check mode reports
 * them; nothing is rewritten unless --write is passed explicitly.
 *
 * Excluded:
 *   - every index.json (generated by build-index.mjs, compact one-line)
 *   - project-type seed files (param-templated `{{...}}` - not JSON on
 *     disk by design; see lib/seeds.mjs)
 *
 * Usage:
 *   node tools/format.mjs           check, report violations, exit 1 if any
 *   node tools/format.mjs --write   rewrite violating files in place
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative, resolve } from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { collectSeedExemptFiles } from './lib/seeds.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..');

function parseArgs(argv) {
  const out = { write: false, root: join(REPO_ROOT, 'data') };
  for (const raw of argv) {
    if (raw === '--write') out.write = true;
    else if (raw === '--check') out.write = false;
    else if (raw.startsWith('--root=')) out.root = resolve(raw.slice('--root='.length));
    else {
      console.error(`format: unknown arg ${raw}`);
      console.error('usage: node tools/format.mjs [--check|--write] [--root=data]');
      process.exit(2);
    }
  }
  return out;
}

function walkJsonFiles(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
  )) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) walkJsonFiles(p, out);
    else if (entry.name.endsWith('.json') && entry.name !== 'index.json') out.push(p);
  }
  return out;
}

function main() {
  const startedAt = Date.now();
  const args = parseArgs(process.argv.slice(2));
  const seedExempt = collectSeedExemptFiles(args.root);

  let total = 0;
  let skippedSeeds = 0;
  let parseFailures = 0;
  const violations = [];

  for (const path of walkJsonFiles(args.root)) {
    if (seedExempt.has(path)) {
      skippedSeeds++;
      continue;
    }
    total++;
    const text = readFileSync(path, 'utf8');
    let canonical;
    try {
      canonical = `${JSON.stringify(JSON.parse(text), null, 2)}\n`;
    } catch {
      // validate.mjs owns parse errors; the formatter just skips them.
      parseFailures++;
      continue;
    }
    if (text !== canonical) violations.push({ path, canonical });
  }

  if (args.write) {
    for (const v of violations) writeFileSync(v.path, v.canonical, 'utf8');
  }

  const elapsed = ((Date.now() - startedAt) / 1000).toFixed(1);
  const verb = args.write ? 'rewrote' : 'found';
  console.log(
    `format: checked ${total} json files (${skippedSeeds} param-templated seeds skipped, ` +
      `${parseFailures} unparseable left to validate.mjs), ${verb} ${violations.length} ` +
      `non-canonical file(s) in ${elapsed}s`,
  );
  if (!args.write && violations.length > 0) {
    for (const v of violations.slice(0, 10)) {
      console.log(`  ${relative(REPO_ROOT, v.path)}`);
    }
    if (violations.length > 10) console.log(`  ... and ${violations.length - 10} more`);
    console.log('run `node tools/format.mjs --write` to rewrite (reflows Biome-styled inline arrays - see file header)');
    process.exit(1);
  }
}

main();
